# CMake generated Testfile for 
# Source directory: /wzz/SHCDB/src
# Build directory: /wzz/SHCDB/src/release
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(c_test "/wzz/SHCDB/src/release/c_test")
set_tests_properties(c_test PROPERTIES  _BACKTRACE_TRIPLES "/wzz/SHCDB/src/CMakeLists.txt;296;add_test;/wzz/SHCDB/src/CMakeLists.txt;299;leveldb_test;/wzz/SHCDB/src/CMakeLists.txt;0;")
add_test(fault_injection_test "/wzz/SHCDB/src/release/fault_injection_test")
set_tests_properties(fault_injection_test PROPERTIES  _BACKTRACE_TRIPLES "/wzz/SHCDB/src/CMakeLists.txt;296;add_test;/wzz/SHCDB/src/CMakeLists.txt;300;leveldb_test;/wzz/SHCDB/src/CMakeLists.txt;0;")
add_test(issue178_test "/wzz/SHCDB/src/release/issue178_test")
set_tests_properties(issue178_test PROPERTIES  _BACKTRACE_TRIPLES "/wzz/SHCDB/src/CMakeLists.txt;296;add_test;/wzz/SHCDB/src/CMakeLists.txt;302;leveldb_test;/wzz/SHCDB/src/CMakeLists.txt;0;")
add_test(issue200_test "/wzz/SHCDB/src/release/issue200_test")
set_tests_properties(issue200_test PROPERTIES  _BACKTRACE_TRIPLES "/wzz/SHCDB/src/CMakeLists.txt;296;add_test;/wzz/SHCDB/src/CMakeLists.txt;303;leveldb_test;/wzz/SHCDB/src/CMakeLists.txt;0;")
add_test(issue320_test "/wzz/SHCDB/src/release/issue320_test")
set_tests_properties(issue320_test PROPERTIES  _BACKTRACE_TRIPLES "/wzz/SHCDB/src/CMakeLists.txt;296;add_test;/wzz/SHCDB/src/CMakeLists.txt;304;leveldb_test;/wzz/SHCDB/src/CMakeLists.txt;0;")
add_test(env_test "/wzz/SHCDB/src/release/env_test")
set_tests_properties(env_test PROPERTIES  _BACKTRACE_TRIPLES "/wzz/SHCDB/src/CMakeLists.txt;296;add_test;/wzz/SHCDB/src/CMakeLists.txt;306;leveldb_test;/wzz/SHCDB/src/CMakeLists.txt;0;")
add_test(status_test "/wzz/SHCDB/src/release/status_test")
set_tests_properties(status_test PROPERTIES  _BACKTRACE_TRIPLES "/wzz/SHCDB/src/CMakeLists.txt;296;add_test;/wzz/SHCDB/src/CMakeLists.txt;307;leveldb_test;/wzz/SHCDB/src/CMakeLists.txt;0;")
add_test(no_destructor_test "/wzz/SHCDB/src/release/no_destructor_test")
set_tests_properties(no_destructor_test PROPERTIES  _BACKTRACE_TRIPLES "/wzz/SHCDB/src/CMakeLists.txt;296;add_test;/wzz/SHCDB/src/CMakeLists.txt;308;leveldb_test;/wzz/SHCDB/src/CMakeLists.txt;0;")
add_test(autocompact_test "/wzz/SHCDB/src/release/autocompact_test")
set_tests_properties(autocompact_test PROPERTIES  _BACKTRACE_TRIPLES "/wzz/SHCDB/src/CMakeLists.txt;296;add_test;/wzz/SHCDB/src/CMakeLists.txt;311;leveldb_test;/wzz/SHCDB/src/CMakeLists.txt;0;")
add_test(corruption_test "/wzz/SHCDB/src/release/corruption_test")
set_tests_properties(corruption_test PROPERTIES  _BACKTRACE_TRIPLES "/wzz/SHCDB/src/CMakeLists.txt;296;add_test;/wzz/SHCDB/src/CMakeLists.txt;312;leveldb_test;/wzz/SHCDB/src/CMakeLists.txt;0;")
add_test(db_test "/wzz/SHCDB/src/release/db_test")
set_tests_properties(db_test PROPERTIES  _BACKTRACE_TRIPLES "/wzz/SHCDB/src/CMakeLists.txt;296;add_test;/wzz/SHCDB/src/CMakeLists.txt;313;leveldb_test;/wzz/SHCDB/src/CMakeLists.txt;0;")
add_test(dbformat_test "/wzz/SHCDB/src/release/dbformat_test")
set_tests_properties(dbformat_test PROPERTIES  _BACKTRACE_TRIPLES "/wzz/SHCDB/src/CMakeLists.txt;296;add_test;/wzz/SHCDB/src/CMakeLists.txt;314;leveldb_test;/wzz/SHCDB/src/CMakeLists.txt;0;")
add_test(filename_test "/wzz/SHCDB/src/release/filename_test")
set_tests_properties(filename_test PROPERTIES  _BACKTRACE_TRIPLES "/wzz/SHCDB/src/CMakeLists.txt;296;add_test;/wzz/SHCDB/src/CMakeLists.txt;315;leveldb_test;/wzz/SHCDB/src/CMakeLists.txt;0;")
add_test(log_test "/wzz/SHCDB/src/release/log_test")
set_tests_properties(log_test PROPERTIES  _BACKTRACE_TRIPLES "/wzz/SHCDB/src/CMakeLists.txt;296;add_test;/wzz/SHCDB/src/CMakeLists.txt;316;leveldb_test;/wzz/SHCDB/src/CMakeLists.txt;0;")
add_test(recovery_test "/wzz/SHCDB/src/release/recovery_test")
set_tests_properties(recovery_test PROPERTIES  _BACKTRACE_TRIPLES "/wzz/SHCDB/src/CMakeLists.txt;296;add_test;/wzz/SHCDB/src/CMakeLists.txt;317;leveldb_test;/wzz/SHCDB/src/CMakeLists.txt;0;")
add_test(skiplist_test "/wzz/SHCDB/src/release/skiplist_test")
set_tests_properties(skiplist_test PROPERTIES  _BACKTRACE_TRIPLES "/wzz/SHCDB/src/CMakeLists.txt;296;add_test;/wzz/SHCDB/src/CMakeLists.txt;318;leveldb_test;/wzz/SHCDB/src/CMakeLists.txt;0;")
add_test(version_edit_test "/wzz/SHCDB/src/release/version_edit_test")
set_tests_properties(version_edit_test PROPERTIES  _BACKTRACE_TRIPLES "/wzz/SHCDB/src/CMakeLists.txt;296;add_test;/wzz/SHCDB/src/CMakeLists.txt;319;leveldb_test;/wzz/SHCDB/src/CMakeLists.txt;0;")
add_test(version_set_test "/wzz/SHCDB/src/release/version_set_test")
set_tests_properties(version_set_test PROPERTIES  _BACKTRACE_TRIPLES "/wzz/SHCDB/src/CMakeLists.txt;296;add_test;/wzz/SHCDB/src/CMakeLists.txt;320;leveldb_test;/wzz/SHCDB/src/CMakeLists.txt;0;")
add_test(write_batch_test "/wzz/SHCDB/src/release/write_batch_test")
set_tests_properties(write_batch_test PROPERTIES  _BACKTRACE_TRIPLES "/wzz/SHCDB/src/CMakeLists.txt;296;add_test;/wzz/SHCDB/src/CMakeLists.txt;321;leveldb_test;/wzz/SHCDB/src/CMakeLists.txt;0;")
add_test(memenv_test "/wzz/SHCDB/src/release/memenv_test")
set_tests_properties(memenv_test PROPERTIES  _BACKTRACE_TRIPLES "/wzz/SHCDB/src/CMakeLists.txt;296;add_test;/wzz/SHCDB/src/CMakeLists.txt;323;leveldb_test;/wzz/SHCDB/src/CMakeLists.txt;0;")
add_test(filter_block_test "/wzz/SHCDB/src/release/filter_block_test")
set_tests_properties(filter_block_test PROPERTIES  _BACKTRACE_TRIPLES "/wzz/SHCDB/src/CMakeLists.txt;296;add_test;/wzz/SHCDB/src/CMakeLists.txt;325;leveldb_test;/wzz/SHCDB/src/CMakeLists.txt;0;")
add_test(table_test "/wzz/SHCDB/src/release/table_test")
set_tests_properties(table_test PROPERTIES  _BACKTRACE_TRIPLES "/wzz/SHCDB/src/CMakeLists.txt;296;add_test;/wzz/SHCDB/src/CMakeLists.txt;326;leveldb_test;/wzz/SHCDB/src/CMakeLists.txt;0;")
add_test(arena_test "/wzz/SHCDB/src/release/arena_test")
set_tests_properties(arena_test PROPERTIES  _BACKTRACE_TRIPLES "/wzz/SHCDB/src/CMakeLists.txt;296;add_test;/wzz/SHCDB/src/CMakeLists.txt;328;leveldb_test;/wzz/SHCDB/src/CMakeLists.txt;0;")
add_test(bloom_test "/wzz/SHCDB/src/release/bloom_test")
set_tests_properties(bloom_test PROPERTIES  _BACKTRACE_TRIPLES "/wzz/SHCDB/src/CMakeLists.txt;296;add_test;/wzz/SHCDB/src/CMakeLists.txt;329;leveldb_test;/wzz/SHCDB/src/CMakeLists.txt;0;")
add_test(cache_test "/wzz/SHCDB/src/release/cache_test")
set_tests_properties(cache_test PROPERTIES  _BACKTRACE_TRIPLES "/wzz/SHCDB/src/CMakeLists.txt;296;add_test;/wzz/SHCDB/src/CMakeLists.txt;330;leveldb_test;/wzz/SHCDB/src/CMakeLists.txt;0;")
add_test(coding_test "/wzz/SHCDB/src/release/coding_test")
set_tests_properties(coding_test PROPERTIES  _BACKTRACE_TRIPLES "/wzz/SHCDB/src/CMakeLists.txt;296;add_test;/wzz/SHCDB/src/CMakeLists.txt;331;leveldb_test;/wzz/SHCDB/src/CMakeLists.txt;0;")
add_test(crc32c_test "/wzz/SHCDB/src/release/crc32c_test")
set_tests_properties(crc32c_test PROPERTIES  _BACKTRACE_TRIPLES "/wzz/SHCDB/src/CMakeLists.txt;296;add_test;/wzz/SHCDB/src/CMakeLists.txt;332;leveldb_test;/wzz/SHCDB/src/CMakeLists.txt;0;")
add_test(hash_test "/wzz/SHCDB/src/release/hash_test")
set_tests_properties(hash_test PROPERTIES  _BACKTRACE_TRIPLES "/wzz/SHCDB/src/CMakeLists.txt;296;add_test;/wzz/SHCDB/src/CMakeLists.txt;333;leveldb_test;/wzz/SHCDB/src/CMakeLists.txt;0;")
add_test(logging_test "/wzz/SHCDB/src/release/logging_test")
set_tests_properties(logging_test PROPERTIES  _BACKTRACE_TRIPLES "/wzz/SHCDB/src/CMakeLists.txt;296;add_test;/wzz/SHCDB/src/CMakeLists.txt;334;leveldb_test;/wzz/SHCDB/src/CMakeLists.txt;0;")
add_test(env_posix_test "/wzz/SHCDB/src/release/env_posix_test")
set_tests_properties(env_posix_test PROPERTIES  _BACKTRACE_TRIPLES "/wzz/SHCDB/src/CMakeLists.txt;296;add_test;/wzz/SHCDB/src/CMakeLists.txt;341;leveldb_test;/wzz/SHCDB/src/CMakeLists.txt;0;")
